name: Correcteur de fautes

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "**/*.txt"
      - "docs/**"

jobs:
  orthographe:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Installer Python et Node.js
      - name: Installer Python et Node
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer outils
        run: |
          pip install codespell
          npm install -g cspell

      # 3️⃣ Config cspell pour le français et le vocabulaire juridique
      - name: Configurer cspell
        run: |
          if [ ! -f cspell.json ]; then
            cat > cspell.json <<'JSON'
            {
              "version": "0.2",
              "language": "fr",
              "dictionaries": ["fr","en"],
              "ignorePaths": [".git","node_modules","**/*.pdf","**/*.png","**/*.jpg"],
              "words": [
                "jurisprudence","pourvoi","cass.","C.civ.","alinéa",
                "L3","TD","UE","droit","arrêt","cons.","CodeCivil","art."
              ]
            }
JSON
          fi

      # 4️⃣ Rapport orthographe avec cspell
      - name: Rapport orthographe (cspell)
        run: |
          echo "=== Rapport cspell ==="
          cspell "**/*.{md,txt}" --no-progress --gitignore --unique || true

      # 5️⃣ Corrections automatiques avec codespell
      - name: Corrections automatiques (codespell)
        run: |
          codespell -w -S "node_modules,*.pdf,*.png,*.jpg,.git" \
            -L "alineas,etat,interet,interets,mutualiser,mutualise" \
            --skip="*.pdf,*.png,*.jpg" .

      # 6️⃣ Rapport grammaire/conjugaison avec LanguageTool
      - name: Rapport grammaire/conjugaison (LanguageTool)
        uses: languagetool-org/languagetool-github-action@v1
        with:
          files: "**/*.md"
          language: "fr"

      # 7️⃣ Vérifier s'il y a des changements et les loguer
      - name: Vérifier changements après correction
        id: changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Fichiers modifiés par codespell :"
            git status --short
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Aucun changement détecté."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

