- name: Ajouter devoirs depuis 1.Agenda.md
  env:
    GC_CREDENTIALS: ${{ secrets.GC_CREDENTIALS }}
  run: |
    python - <<'EOF'
    import os
    import json
    import re
    from google.oauth2 import service_account
    from googleapiclient.discovery import build

    # Connexion Google Calendar
    SCOPES = ["https://www.googleapis.com/auth/calendar"]
    creds_dict = json.loads(os.environ["GC_CREDENTIALS"])
    creds = service_account.Credentials.from_service_account_info(creds_dict, scopes=SCOPES)
    service = build("calendar", "v3", credentials=creds)

    # Lire le fichier 1.Agenda.md
    filename = "1.Agenda.md"
    try:
        with open(filename, "r", encoding="utf-8") as f:
            agenda = f.read()
    except FileNotFoundError:
        print(f"⚠️ Fichier {filename} non trouvé !")
        exit(1)

    # Extraire les devoirs au format "YYYY-MM-DD - Titre"
    pattern = r"(\d{4}-\d{2}-\d{2}) - (.+)"
    matches = re.findall(pattern, agenda)

    if not matches:
        print("⚠️ Aucun devoir trouvé dans 1.Agenda.md")
        exit(0)

    for date_str, title in matches:
        # Événement sur toute la journée
        event = {
            'summary': title,
            'start': {'date': date_str},
            'end': {'date': date_str},
        }

        # Ajouter l'événement
        service.events().insert(calendarId='primary', body=event).execute()
        print(f"✅ Devoir ajouté : {date_str} - {title}")
    EOF

