name: Correcteur d'orthographe

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "**/*.txt"
      - "docs/**"
  workflow_dispatch:  # permet de lancer manuellement

jobs:
  orthographe:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3️⃣ Installer cspell
      - name: Installer cspell
        run: npm install -g cspell

      # 4️⃣ Configurer cspell pour français et vocabulaire juridique
      - name: Configurer cspell
        run: |
          if [ ! -f cspell.json ]; then
            echo '{
              "version": "0.2",
              "language": "fr",
              "dictionaries": ["fr","en"],
              "ignorePaths": [".git","node_modules","**/*.pdf","**/*.png","**/*.jpg"],
              "words": [
                "jurisprudence","pourvoi","cass.","C.civ.","alinéa",
                "L3","TD","UE","droit","arrêt","cons.","CodeCivil","art."
              ]
            }' > cspell.json
          fi

      # 5️⃣ Rapport orthographe
      - name: Rapport orthographe (cspell)
        run: |
          echo "=== Rapport cspell ==="
          cspell "**/*.{md,txt}" --no-progress --gitignore --unique || true

