name: Correcteur de fautes

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "**/*.txt"
      - "docs/**"

jobs:
  rapport:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer cspell
        run: npm install -g cspell

      - name: Configurer cspell
        run: |
          if [ ! -f cspell.json ]; then
            echo '{
              "version": "0.2",
              "language": "fr",
              "dictionaries": ["fr","en"],
              "ignorePaths": [".git","node_modules","**/*.pdf","**/*.png","**/*.jpg"],
              "words": [
                "jurisprudence","pourvoi","cass.","C.civ.","alinéa",
                "L3","TD","UE","droit","arrêt","cons.","CodeCivil","art."
              ]
            }' > cspell.json

      - name: Rapport orthographe (cspell)
        run: |
          echo "=== Rapport cspell ==="
          cspell "**/*.{md,txt}" --no-progress --gitignore --unique || true

      - name: Rapport grammaire/conjugaison (LanguageTool)
        run: |
          echo "=== Rapport LanguageTool ==="
          docker run --rm -v $PWD:/data silviof/docker-languagetool languagetool /data/**/*.md -l fr

