name: Notify Discord on Push

on:
  push:
    branches:
      - main   # Remplace par la branche que tu veux surveiller

jobs:
  discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        uses: actions/http-client@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          headers: '{"Content-Type":"application/json"}'
          body: |
            {
              "content": "Le repo a été mis à jour ! Commit: ${{ github.sha }} par ${{ github.actor }}. Voir les détails : ${{ github.event.head_commit.url }}"
            }
