name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"Le repo a été mis à jour ! Commit: $GITHUB_SHA par $GITHUB_ACTOR. Voir les détails : $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
